Repository codesquad-project-team/frontend, pull requests merged in 2019-10, with the labels that each got.

#13 [2-2] 포스트 디테일 설명 구현 / [2-4] 장소 이미지 캐러셀 구현 / [2-5] 관련 포스트 리스트 구현
  package.json
  src/components/DetailPost/DetailPost.jsx
  src/components/DetailPost/DetailPost.scss
  src/components/LocationCarousel/LocationCarousel.jsx
  src/components/LocationCarousel/LocationCarousel.scss
  src/components/RelatedPost/RelatedPost.jsx
  src/components/RelatedPost/RelatedPost.scss
  src/components/RelatedPostComment/RelatedPostComment.jsx
  src/components/RelatedPostComment/RelatedPostComment.scss
  src/index.jsx
  src/pages/DetailPage/DetailPage.jsx
  webpack.config.js
  webpack.config.prod.js
  yarn.lock
Labels: enhancement

#9 [2-1] 장소 디테일 페이지 - 헤더 구현
  resources/magnifier_icon.png
  src/components/Header/CommonBtn.jsx
  src/components/Header/CommonBtn.scss
  src/components/Header/Header.jsx
  src/components/Header/Header.scss
  src/hooks/useInput.jsx
  src/pages/DetailPage/DetailPage.jsx
Labels: enhancement

#10 [2-3] 장소 디테일 페이지 - 맵 구현
  .gitignore
  package.json
  resources/info-window-arrow.png
  resources/times-solid.png
  src/components/MapView/InfoWindow.jsx
  src/components/MapView/InfoWindow.scss
  src/components/MapView/MapView.jsx
  src/pages/DetailPage/DetailPage.jsx
  yarn.lock
Labels: enhancement

#14 [2] 장소 디테일 페이지 구현
  .eslintrc.js
  .gitignore
  package.json
  resources/info-window-arrow.png
  resources/magnifier_icon.png
  resources/times-solid.png
  src/Root.jsx
  src/components/DetailPost/DetailPost.jsx
  src/components/DetailPost/DetailPost.scss
  src/components/Header/CommonBtn.jsx
  src/components/Header/CommonBtn.scss
  src/components/Header/Header.jsx
  src/components/Header/Header.scss
  src/components/LocationCarousel/LocationCarousel.jsx
  src/components/LocationCarousel/LocationCarousel.scss
  src/components/MapView/InfoWindow.jsx
  src/components/MapView/InfoWindow.scss
  src/components/MapView/MapView.jsx
  src/components/ProfileImage/ProfileImage.jsx
  src/components/ProfileImage/ProfileImage.scss
  src/components/RelatedPost/RelatedPost.jsx
  src/components/RelatedPost/RelatedPost.scss
  src/components/RelatedPostComment/RelatedPostComment.jsx
  src/components/RelatedPostComment/RelatedPostComment.scss
  src/hooks/useInput.jsx
  src/index.html
  src/index.jsx
  src/pages/DetailPage/DetailPage.jsx
  src/pages/DetailPage/DetailPage.scss
  src/stylesheets/base.scss
  src/utils/utils.js
  webpack.config.js
  webpack.config.prod.js
  yarn.lock
Labels: enhancement

#18 [4] ProfileImage 컴포넌트에 props를 넣어도 적용되지 않는 이슈 해결
  .eslintrc.js
  src/components/DetailPost/DetailPost.scss
  src/components/ProfileImage/ProfileImage.jsx
  src/components/ProfileImage/ProfileImage.scss
  src/configs.js
Labels: bug

#20 [5] 회원가입 모달창 구현 / [7] 로그인 모달창 구현
  src/Root.jsx
  src/components/CommonModal/CommonModal.jsx
  src/components/CommonModal/CommonModal.scss
  src/components/Header/Header.jsx
  src/components/OAuthBtn/OAuthBtn.jsx
  src/components/OAuthBtn/OAuthBtn.scss
  src/components/RelatedPost/RelatedPost.jsx
  src/pages/LoginPage/LoginPage.jsx
Labels: new feature

#21 [6] 회원 정보 수정 페이지 구현
  src/Root.jsx
  src/components/ProfileContentItem/ProfileContentItem.jsx
  src/components/ProfileContentItem/ProfileContentItem.scss
  src/hooks/useInput.jsx
  src/pages/ProfileEditPage/ProfileEditPage.jsx
  src/pages/ProfileEditPage/ProfileEditPage.scss
Labels: new feature

#22 [3] 메인 페이지 구현
  babel.config.js
  package.json
  src/components/Header/Header.scss
  src/components/PostContainer/PostContainer.jsx
  src/components/PostContainer/PostContainer.scss
  src/components/PostItem/PostItem.jsx
  src/components/PostItem/PostItem.scss
  src/configs.js
  src/hooks/useFetch.jsx
  src/pages/DetailPage/DetailPage.scss
  src/pages/MainPage/MainPage.jsx
  src/pages/MainPage/MainPage.scss
  yarn.lock
Labels: new feature

#29 [12] 디자인 초기 세팅 및 메인, 디테일 페이지 디자인
  src/components/DetailPost/DetailPost.jsx
  src/components/Header/CommonBtn.scss
  src/components/Header/Header.jsx
  src/components/Header/Header.scss
  src/components/PostContainer/PostContainer.scss
  src/components/PostItem/PostItem.scss
  src/configs.js
  src/index.html
  src/index.jsx
  src/pages/DetailPage/DetailPage.jsx
  src/pages/DetailPage/DetailPage.scss
  src/pages/MainPage/MainPage.jsx
  src/pages/MainPage/MainPage.scss
  src/stylesheets/base.scss
  src/stylesheets/util.scss
Labels: refactor/style

#34 [8] detail page에 fetch 코드 추가
  README.md
  src/Root.jsx
  src/components/DetailPost/DetailPost.jsx
  src/components/LocationCarousel/LocationCarousel.jsx
  src/components/RelatedPost/RelatedPost.jsx
  src/components/RelatedPost/RelatedPostComment.jsx
  src/components/RelatedPostComment/RelatedPostComment.scss
  src/configs.js
  src/pages/DetailPage/DetailPage.jsx
  src/pages/DetailPage/DetailPage.scss
Labels: new feature

#32 [10] 개인 프로필 페이지 구현
  src/Root.jsx
  src/components/CommonBtn/CommonBtn.jsx
  src/components/CommonBtn/CommonBtn.scss
  src/components/Header/CommonBtn.scss
  src/components/Header/Header.jsx
  src/components/Header/Header.scss
  src/components/NewPostBtn/NewPostBtn.jsx
  src/components/NewPostBtn/NewPostBtn.scss
  src/components/PostContainer/PostContainer.jsx
  src/components/ProfileImage/ProfileImage.jsx
  src/components/ProfileInfo/ProfileInfo.jsx
  src/components/ProfileInfo/ProfileInfo.scss
  src/configs.js
  src/hooks/useFetch.jsx
  src/pages/DetailPage/DetailPage.scss
  src/pages/MainPage/MainPage.jsx
  src/pages/MainPage/MainPage.scss
  src/pages/ProfilePage/ProfilePage.jsx
  src/pages/ProfilePage/ProfilePage.scss
  src/utils/utils.js
  webpack.config.js
  webpack.config.prod.js
Labels: new feature

#36 [13] 회원 정보 수정 페이지와 모달창에 통일된 디자인 반영
  resources/facebook-logo.png
  resources/insta-logo.png
  resources/kakao-logo.png
  resources/logo.png
  src/components/CommonModal/CommonModal.jsx
  src/components/CommonModal/CommonModal.scss
  src/components/OAuthBtn/OAuthBtn.jsx
  src/components/OAuthBtn/OAuthBtn.scss
  src/components/ProfileContentItem/ProfileContentItem.scss
  src/pages/ProfileEditPage/ProfileEditPage.jsx
  src/pages/ProfileEditPage/ProfileEditPage.scss
  src/stylesheets/util.scss
Labels: refactor/style
