Repository codesquad-project-team/frontend, pull requests merged in 2019-11, with the labels that each got.

#44 [14] PostItem을 클릭 했을 때 스크롤이 최상단으로 이동하는 기능 추가
  src/components/PostContainer/PostContainer.jsx
Labels: new feature

#46 [18] CommonBtn 상황에 맞게 사용하도록 커스텀 코드 추가
  src/components/CommonBtn/CommonBtn.jsx
  src/components/CommonBtn/CommonBtn.scss
  src/components/CommonModal/CommonModal.jsx
  src/components/CommonModal/CommonModal.scss
  src/components/Header/Header.jsx
  src/components/OAuthBtn/OAuthBtn.jsx
  src/components/OAuthBtn/OAuthBtn.scss
  src/components/ProfileInfo/ProfileInfo.jsx
  src/components/ProfileInfo/ProfileInfo.scss
  src/pages/ProfileEditPage/ProfileEditPage.jsx
  src/pages/ProfileEditPage/ProfileEditPage.scss
  src/stylesheets/util.scss
Labels: new feature, refactor/style

#45 [15] 로고에 라우터 링크 추가
  src/Root.jsx
  src/components/CommonModal/CommonModal.jsx
  src/components/Header/Header.jsx
  src/components/Header/Header.scss
  src/components/OAuthBtn/OAuthBtn.jsx
  src/components/OAuthBtn/OAuthBtn.scss
Labels: new feature

#43 [11] 포스트 작성 페이지 마크업
  src/Root.jsx
  src/components/CommonBtn/CloseBtn.jsx
  src/components/CommonBtn/CloseBtn.scss
  src/components/CommonPost/CommonPost.jsx
  src/components/CommonPost/CommonPost.scss
  src/components/Header/Header.jsx
  src/components/Header/Header.scss
  src/components/PostUploader/CommentUploader.jsx
  src/components/PostUploader/CommentUploader.scss
  src/components/PostUploader/ImageUploader.jsx
  src/components/PostUploader/ImageUploader.scss
  src/components/PostUploader/LocationFinder.jsx
  src/components/PostUploader/LocationFinder.scss
  src/components/PostUploader/LocationUploader.jsx
  src/components/PostUploader/PostQuestions.jsx
  src/components/PostUploader/PostQuestions.scss
  src/components/PostUploader/TitleUploader.jsx
  src/components/PostUploader/TitleUploader.scss
  src/hooks/useInput.jsx
  src/hooks/useModal.jsx
  src/hooks/useModal.scss
  src/pages/PostUploadPage/PostUploadPage.jsx
  src/pages/PostUploadPage/PostUploadPage.scss
  src/pages/ProfileEditPage/ProfileEditPage.jsx
  src/pages/ProfilePage/ProfilePage.jsx
  src/stylesheets/util.scss
  src/utils/utils.js
Labels: new feature

#48 [20] 프로필 편집버튼 텍스트가 가운데 정렬되지 않는 이슈 해결
  src/components/CommonModal/CommonModal.scss
  src/components/ProfileInfo/ProfileInfo.jsx
  src/components/ProfileInfo/ProfileInfo.scss
Labels: refactor/style

#51 [17] 글 작성 버튼 위에 툴팁 추가
  src/components/NewPostBtn/NewPostBtn.jsx
  src/components/NewPostBtn/ToolTip.jsx
  src/components/NewPostBtn/ToolTip.scss
Labels: new feature

#53 [22] 사용자의 profile-content를 fetch를 통해 받아오는 기능 추가
  src/components/ProfileInfo/ProfileInfo.jsx
  src/pages/ProfilePage/ProfilePage.jsx
Labels: new feature

#59 [25] 회원가입 페이지(닉네임입력) 구현
  src/Root.jsx
  src/pages/SignupPage/SignupPage.jsx
  src/pages/SignupPage/SignupPage.scss
  src/utils/utils.js
Labels: new feature

#62 [23] 포스트 작성 페이지에서 이미지를 S3에 올리는 기능 및 유동적인 UI 구현
  .gitignore
  package.json
  src/components/PostUploader/ImageUploader.jsx
  src/components/PostUploader/ImageUploader.scss
  src/components/PostUploader/ImageUploader/FirstInputButton.jsx
  src/components/PostUploader/ImageUploader/FirstInputButton.scss
  src/components/PostUploader/ImageUploader/ImageUploader.jsx
  src/components/PostUploader/ImageUploader/ImageUploader.scss
  src/components/PostUploader/ImageUploader/PreviewImages.jsx
  src/components/PostUploader/ImageUploader/PreviewImages.scss
  src/components/PostUploader/ImageUploader/SecondInputButton.jsx
  src/components/PostUploader/ImageUploader/SecondInputButton.scss
  src/hooks/useS3.jsx
  src/pages/PostUploadPage/PostUploadPage.jsx
  src/utils/utils.js
  webpack.config.js
  yarn.lock
Labels: new feature, refactor/style

#61 [28] 회원가입 기능 및 가입 이후 로그인 과정 구현
  src/Root.jsx
  src/components/CommonLink/CommonLink.jsx
  src/components/CommonLink/CommonLink.scss
  src/components/Header/Header.jsx
  src/components/Header/Header.scss
  src/components/NewPostBtn/NewPostBtn.jsx
  src/components/PostContainer/PostContainer.jsx
  src/components/PostContainer/PostContainer.scss
  src/components/ProfileInfo/ProfileInfo.jsx
  src/components/ProfileInfo/ProfileInfo.scss
  src/contexts/LoginContext.jsx
  src/hooks/useFetch.jsx
  src/hooks/useShakeAnimation.jsx
  src/hooks/useShakeAnimation.scss
  src/hooks/useTempTokenValidation.jsx
  src/pages/ProfilePage/ProfilePage.jsx
  src/pages/SignupPage/SignupPage.jsx
  src/pages/SignupPage/SignupPage.scss
  src/pages/SignupPage/ValidityMessage.jsx
  src/pages/SignupPage/ValidityMessage.scss
Labels: new feature, refactor/style
