Repository codesquad-project-team/frontend, pull requests merged in 2019-12, with the labels that each got.

#68 [27] 카카오 지도로 변경 및 장소 검색 기능 구현
  package.json
  src/components/CommonBtn/CommonBtn.jsx
  src/components/MapView/InfoWindow.jsx
  src/components/MapView/InfoWindow.scss
  src/components/MapView/MapView.jsx
  src/components/PostUploader/LocationFinder.jsx
  src/components/PostUploader/LocationUploader.jsx
  src/components/PostUploader/LocationUploader/LocationFindButton.jsx
  src/components/PostUploader/LocationUploader/LocationFindButton.scss
  src/components/PostUploader/LocationUploader/LocationFinder.jsx
  src/components/PostUploader/LocationUploader/LocationFinder.scss
  src/components/PostUploader/LocationUploader/LocationFinderPopupMessage.jsx
  src/components/PostUploader/LocationUploader/LocationFinderPopupMessage.scss
  src/components/PostUploader/LocationUploader/LocationPreview.jsx
  src/components/PostUploader/LocationUploader/LocationUploader.jsx
  src/components/PostUploader/LocationUploader/MarkerController.jsx
  src/components/PostUploader/LocationUploader/MarkerInfoWindow.jsx
  src/components/PostUploader/LocationUploader/MarkerInfoWindow.scss
  src/components/PostUploader/LocationUploader/SearchResultLists.jsx
  src/components/PostUploader/LocationUploader/SearchResultLists.scss
  src/components/PostUploader/LocationUploader/SearchResultMarkers.jsx
  src/components/PostUploader/LocationUploader/react-kakao-maps/CustomOverlay/index.jsx
  src/components/PostUploader/LocationUploader/react-kakao-maps/CustomOverlayContainer/index.jsx
  src/components/PostUploader/LocationUploader/react-kakao-maps/Marker/index.jsx
  src/components/PostUploader/LocationUploader/react-kakao-maps/constants.js
  src/components/PostUploader/LocationUploader/react-kakao-maps/hooks/useMapContext.jsx
  src/components/PostUploader/LocationUploader/react-kakao-maps/hooks/usePlaceService.jsx
  src/components/PostUploader/TitleUploader.jsx
  src/hooks/useModal.jsx
  src/pages/PostUploadPage/PostUploadPage.jsx
  src/utils/utils.js
  webpack.config.js
  webpack.config.prod.js
  yarn.lock
Labels: new feature, refactor/style

#66 [31] AWS 객체 보안 강화
  src/components/PostUploader/ImageUploader/ImageUploader.jsx
  src/hooks/useS3.jsx
  src/hooks/useScript.jsx
  src/pages/PostUploadPage/PostUploadPage.jsx
Labels: new feature, refactor/style

#75 [docs] readme.md 업데이트(travis, webpack 기술 스택 추가, git 브랜치전략 추가)
  README.md
Labels: documentation

#72 [30] 회원 정보 수정 페이지 기능 구현
  src/components/PostUploader/ImageUploader/ImageUploader.jsx
  src/components/ProfileContentItem/ProfileContentItem.jsx
  src/components/ProfileContentItem/ProfileContentItem.scss
  src/components/ValidityMessage/ValidityMessage.jsx
  src/components/ValidityMessage/ValidityMessage.scss
  src/hooks/useInput.jsx
  src/hooks/useS3.jsx
  src/hooks/useScript.jsx
  src/pages/PostUploadPage/PostUploadPage.jsx
  src/pages/ProfileEditPage/ProfileEditPage.jsx
  src/pages/ProfileEditPage/ProfileEditPage.scss
  src/pages/ProfileEditPage/ProfileImageChangeBtn.jsx
  src/pages/ProfileEditPage/ProfileImageChangeBtn.scss
  src/pages/SignupPage/SignupPage.jsx
Labels: new feature

#73 [33] 팔로우/언팔로우 기능 구현 및 프로필 페이지의 포스트 목록 api 수정
  src/Root.jsx
  src/components/Header/Header.jsx
  src/components/PostContainer/PostContainer.jsx
  src/components/ProfileInfo/ProfileInfo.jsx
  src/contexts/LoginContext.jsx
  src/contexts/LoginModalContext.jsx
  src/pages/ProfilePage/ProfilePage.jsx
Labels: new feature

#78 [29] 포스트 업로드 기능 구현
  src/Root.jsx
  src/components/DetailPost/DetailPost.jsx
  src/components/PostItem/PostItem.jsx
  src/components/PostUploader/CommentUploader.jsx
  src/components/PostUploader/CommentUploader.scss
  src/components/PostUploader/DescriptionUploader.jsx
  src/components/PostUploader/DescriptionUploader.scss
  src/components/PostUploader/ImageUploader/FirstInputButton.scss
  src/components/PostUploader/ImageUploader/ImageUploader.jsx
  src/components/PostUploader/LocationUploader/LocationFindButton.scss
  src/components/PostUploader/LocationUploader/LocationFinder.jsx
  src/components/PostUploader/LocationUploader/LocationUploader.jsx
  src/components/PostUploader/TitleUploader.jsx
  src/components/PostUploader/TitleUploader.scss
  src/hooks/useS3.jsx
  src/pages/PostUploadPage/PostUploadPage.jsx
  src/pages/PostUploadPage/PostUploadPage.scss
Labels: new feature

#83 [41] 크롬 업데이트에 따른 전체 폰트사이즈 수정
  src/components/CommonModal/CommonModal.scss
  src/components/DetailPost/DetailPost.scss
  src/components/Header/Header.scss
  src/components/OAuthBtn/OAuthBtn.scss
  src/components/PostItem/PostItem.scss
  src/components/PostUploader/DescriptionUploader.scss
  src/components/PostUploader/LocationUploader/LocationFinder.scss
  src/components/PostUploader/LocationUploader/LocationFinderPopupMessage.scss
  src/components/PostUploader/LocationUploader/MarkerInfoWindow.scss
  src/components/PostUploader/LocationUploader/SearchResultLists.scss
  src/components/PostUploader/PostQuestions.scss
  src/components/PostUploader/TitleUploader.scss
  src/components/ProfileContentItem/ProfileContentItem.scss
  src/components/ProfileInfo/ProfileInfo.scss
  src/components/RelatedPost/RelatedPost.scss
  src/components/RelatedPost/RelatedPostComment.scss
  src/pages/MainPage/MainPage.scss
  src/pages/ProfileEditPage/ProfileEditPage.scss
  src/stylesheets/base.scss
Labels: bug, refactor/style

#86 [32] 동일한 이미지를 여러 개 업로드 했을 시에, 대표 이미지 및 삭제할 이미지 선택 버그 발생
  src/components/PostUploader/ImageUploader/ImageUploader.jsx
  src/components/PostUploader/ImageUploader/PreviewImages.jsx
Labels: bug

#84 [35] 다른 사용자의 프로필이미지와 닉네임 클릭시 해당 프로필페이지로 이동하는 기능 추가
  src/components/CommonLink/CommonLink.jsx
  src/components/DetailPost/DetailPost.jsx
  src/components/Header/Header.jsx
  src/components/PostContainer/PostContainer.jsx
  src/components/PostItem/PostItem.jsx
  src/components/PostItem/PostItem.scss
  src/pages/MainPage/MainPage.jsx
  src/pages/ProfilePage/ProfilePage.jsx
Labels: new feature

#85 [34] Header에 드롭다운 메뉴 추가
  src/components/Header/DropdownMenu.jsx
  src/components/Header/DropdownMenu.scss
  src/components/Header/Header.jsx
  src/components/Header/Header.scss
  src/components/ProfileInfo/ProfileInfo.jsx
Labels: new feature, refactor/style

#88 [docs/style] Readme 및 MainPage 메인 문구 수정
  README.md
  src/pages/MainPage/MainPage.jsx
  src/pages/MainPage/MainPage.scss
Labels: documentation, refactor/style
