Repository codesquad-project-team/frontend, pull requests merged in 2020-01, with the labels that each got.

#93 [45] 글자수 초과되지 않았는데 초과했다고 나오는 버그 수정
  src/components/PostUploader/DescriptionUploader.jsx
Labels: bug

#95 [46] 무한스크롤 버그, 관련 포스트 목록 버그 등 수정
  src/components/DetailPost/DetailPost.jsx
  src/components/PostContainer/PostContainer.jsx
  src/components/PostUploader/TitleUploader.scss
  src/components/RelatedPost/RelatedPost.jsx
  src/pages/DetailPage/DetailPage.jsx
Labels: bug

#89 [36] 로그아웃 기능 구현
  src/components/Header/DropdownMenu.jsx
  src/contexts/LoginContext.jsx
Labels: new feature

#96 [44] LoginModal 관련 이슈 로직 수정
  src/Root.jsx
  src/components/CommonModal/CommonModal.jsx
  src/components/CommonModal/CommonModal.scss
  src/components/Header/Header.jsx
  src/components/ProfileInfo/ProfileInfo.jsx
  src/contexts/LoginContext.jsx
  src/contexts/LoginModalContext.jsx
Labels: refactor/style

#98 [42] 포스트 수정 삭제 기능 구현
  src/Root.jsx
  src/components/DetailPostHeader/DetailPostHeader.jsx
  src/components/DetailPostHeader/DetailPostHeader.scss
  src/components/LocationCarousel/LocationCarousel.jsx
  src/components/PostUploader/ImageUploader/ImageUploader.jsx
  src/components/PostUploader/ImageUploader/ImageUploader.scss
  src/components/PostUploader/ImageUploader/SecondInputButton.scss
  src/components/PostUploader/LocationUploader/LocationFinder.jsx
  src/components/PostUploader/TitleUploader.jsx
  src/hooks/useInput.jsx
  src/pages/DetailPage/DetailPage.jsx
  src/pages/PostUploadPage/PostUploadPage.jsx
  src/utils/diff.js
  src/utils/diff.spec.js
  yarn.lock
Labels: new feature
